In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
x, y = np.arange(10).reshape((5,2)), range(5)

In [4]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=0)

In [7]:
x_train

array([[2, 3],
       [6, 7],
       [8, 9]])

In [8]:
x_test

array([[4, 5],
       [0, 1]])

In [9]:
y_train

[1, 3, 4]

In [10]:
y_test

[2, 0]